create table if not exists public.members (
  id bigint generated by default as identity primary key,
  member_id text unique,
  verification_token text unique,
  full_name text not null,
  email text not null,
  email_normalized text not null unique,
  mobile text not null,
  mobile_normalized text not null unique,
  city text not null,
  locality text not null default '',
  age_group text not null default '',
  primary_interest text not null default '',
  plan_id text not null,
  plan_price_paise integer not null,
  status text not null default 'pending_payment',
  password_hash text not null,
  password_salt text not null,
  password_iterations integer not null default 210000,
  issued_at timestamptz,
  valid_until timestamptz,
  consent_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id text primary key,
  member_row_id bigint not null references public.members(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  user_agent_hash text not null default ''
);
create index if not exists sessions_member_idx on public.sessions (member_row_id);
create index if not exists sessions_expiry_idx on public.sessions (expires_at);

create table if not exists public.payment_orders (
  id text primary key,
  member_row_id bigint not null references public.members(id) on delete cascade,
  purpose text not null,
  reference_id text not null,
  amount_paise integer not null,
  currency text not null default 'INR',
  status text not null default 'created',
  gateway_order_id text unique,
  gateway_payment_id text unique,
  metadata_json text not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz
);
create index if not exists payment_orders_member_idx on public.payment_orders (member_row_id);
create index if not exists payment_orders_status_idx on public.payment_orders (status);

create table if not exists public.orders (
  id text primary key,
  member_row_id bigint not null references public.members(id) on delete cascade,
  payment_order_id text references public.payment_orders(id),
  status text not null default 'payment_pending',
  subtotal_paise integer not null,
  total_paise integer not null,
  shipping_json text not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_member_idx on public.orders (member_row_id);
create index if not exists orders_status_idx on public.orders (status);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  item_slug text not null,
  title_snapshot text not null,
  quantity integer not null,
  unit_price_paise integer not null,
  line_total_paise integer not null
);
create index if not exists order_items_order_idx on public.order_items (order_id);

create table if not exists public.bookings (
  id text primary key,
  member_row_id bigint not null references public.members(id) on delete cascade,
  payment_order_id text references public.payment_orders(id),
  source_type text not null,
  source_slug text not null,
  title_snapshot text not null,
  amount_paise integer not null default 0,
  attendee_count integer not null default 1,
  requested_date text,
  requested_time text,
  status text not null default 'payment_pending',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists bookings_member_idx on public.bookings (member_row_id);
create index if not exists bookings_status_idx on public.bookings (status);

create table if not exists public.form_submissions (
  id text primary key,
  type text not null,
  member_row_id bigint references public.members(id) on delete set null,
  name text not null,
  contact text not null,
  data_json text not null,
  status text not null default 'new',
  consent_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists form_submissions_type_idx on public.form_submissions (type);
create index if not exists form_submissions_status_idx on public.form_submissions (status);

create table if not exists public.password_reset_requests (
  id text primary key,
  member_row_id bigint references public.members(id) on delete cascade,
  contact text not null,
  status text not null default 'requested',
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists password_reset_member_idx on public.password_reset_requests (member_row_id);

create table if not exists public.rate_limits (
  key text primary key,
  count integer not null default 0,
  window_start integer not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id text primary key,
  member_row_id bigint references public.members(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text not null default '',
  metadata_json text not null default '{}',
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_member_idx on public.audit_logs (member_row_id);
create index if not exists audit_logs_action_idx on public.audit_logs (action);
